version: '3.5'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  db:
    image: mysql:8.0.33
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - '13306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: paran_sample
      MYSQL_USER: paran
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
      LC_ALL: C.UTF-8