apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot3-sample
  labels:
    app: spring-boot3-sample
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot3-sample
  template:
    metadata:
      labels:
        app: spring-boot3-sample
    spec:
      containers:
        - name: spring-boot3-sample
          image: docker.io/devprkim/spring-boot3-sample:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: spring-boot3-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
      name: http